worker_processes auto;

events{
    worker_connections 1024;
}

http{

include /etc/nginx/mime.types;
default_type application/octet-stream;

sendfile on;
upstream app_server{

    server 127.0.0.1:3000;
}
server{

listen 80;
listen [::]:80;
server_name aichatbotsite.com www.aichatbotsite.com;


location /{

proxy_pass http://app_server;
proxy_http_version 1.1;
proxy_set_header Host $host;



}


}











}
